### ISSUE TITLE
Hello! diboard project released! Here is my suggestions.

### ISSUE THREAD

**Issue by Anoncheg1** [majestrate/nntpchan#146]
Hello! I am released my Java nntp imageboard project:
 [diboard](https://github.com/Anoncheg1/diboard)

Here is what I found:

1. Because of different number of pages and threads per group at different peers some threads removed. When you receive article and REFERENCES header point to missing thread. You must request it to save integrity. I call it "partial threads" in documentation.
2. I made short links inside message. Do you remember short links and global links exchange? I wrote everything in documentation but in Russian. I need time to translate.
3. You have two names for web and nntp in your nntpchan. Make it one.

Take a look at diagrams I made  [dibd](https://github.com/Anoncheg1/dibd)

Thank you very much for your project. I took a lot from your project.
I am in touch.

**Comment by majestrate** [comment]
Very nice work, love to see this happening.

Some feedback on your 3 points:

1. we already try requesting a root post we don't have but it doesn't always work as it may be that all our neighbors don't have it.

2. translation would help, please do when you can

3. this is a historical design choice, it used to be that the web ui and nntp daemon were 2 separate daemons hence different names, i should probably change that.


Additional feedback:

* The crypto signing is the key feature that makes everything sane, the problem is we use nonstandard signatures, perhaps you could chose a standard signature algorithm and i'll add that to my implementation so they can inter operate.

* for flood mitigation we currently don't have much, hence why peering is sensetive information. we have something similar to DKIM to help with that in the future but that needs a lot more work.

**Comment by Anoncheg1** [comment]
- Please explain me "signing". Why it is the key feature? It is Tripcodes?

- What flood do you mean? From peers of from users? Do you thinking about to create digital signed peer articles?
